<?php

namespace ContainerTPeogIZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_VichUploader_Command_MappingDebug_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.vich_uploader.command.mapping_debug.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.vich_uploader.command.mapping_debug.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('vich:mapping:debug', [], 'Debug a mapping.', false, #[\Closure(name: 'vich_uploader.command.mapping_debug', class: 'Vich\\UploaderBundle\\Command\\MappingDebugCommand')] fn (): \Vich\UploaderBundle\Command\MappingDebugCommand => ($container->privates['vich_uploader.command.mapping_debug'] ?? $container->load('getVichUploader_Command_MappingDebugService')));
    }
}
