<?php

namespace Container9A8BFwi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectImageTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ProjectImageType' shared autowired service.
     *
     * @return \App\Form\ProjectImageType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ProjectImageType.php';

        return $container->privates['App\\Form\\ProjectImageType'] = new \App\Form\ProjectImageType();
    }
}
