<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVtDkcyZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVtDkcyZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVtDkcyZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVtDkcyZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVtDkcyZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'VtDkcyZ',
    'container.build_id' => '132c24a3',
    'container.build_time' => 1789420099,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVtDkcyZ');
