<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9A8BFwi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9A8BFwi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9A8BFwi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9A8BFwi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9A8BFwi\App_KernelDevDebugContainer([
    'container.build_hash' => '9A8BFwi',
    'container.build_id' => 'fd9a4783',
    'container.build_time' => 1789504482,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9A8BFwi');
