<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAyiAXOo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAyiAXOo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAyiAXOo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAyiAXOo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAyiAXOo\App_KernelDevDebugContainer([
    'container.build_hash' => 'AyiAXOo',
    'container.build_id' => '681a93a0',
    'container.build_time' => 1789075501,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAyiAXOo');
